name: wasil_tech_task
description: A Flutter app that displays products with cart and authentication functionality.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  get_it: ^8.0.3
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0+1
  cherry_toast: ^1.13.0
  shared_preferences: ^2.5.3
  internet_connection_checker_plus: ^2.7.2
  intl : ^0.18.0
  dartz: ^0.10.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true