// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYYTttZe41_BsZ9xnVxXiesQGoPIbbBD4',
    appId: '1:506716032293:web:0131d6b9d20fa593fedecc',
    messagingSenderId: '506716032293',
    projectId: 'wasil-tech-task-5e36d',
    authDomain: 'wasil-tech-task-5e36d.firebaseapp.com',
    storageBucket: 'wasil-tech-task-5e36d.firebasestorage.app',
    measurementId: 'G-54MFSS8HCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEG6hiIgY8bq8K5-f2ZvfkH12d3teF19s',
    appId: '1:506716032293:android:91341cf98c8642a2fedecc',
    messagingSenderId: '506716032293',
    projectId: 'wasil-tech-task-5e36d',
    storageBucket: 'wasil-tech-task-5e36d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5TmFK8832Gt7EyafG9ru3hgr_qbJWgtU',
    appId: '1:506716032293:ios:aae509e6807e99fafedecc',
    messagingSenderId: '506716032293',
    projectId: 'wasil-tech-task-5e36d',
    storageBucket: 'wasil-tech-task-5e36d.firebasestorage.app',
    iosBundleId: 'com.example.wasilTechTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5TmFK8832Gt7EyafG9ru3hgr_qbJWgtU',
    appId: '1:506716032293:ios:aae509e6807e99fafedecc',
    messagingSenderId: '506716032293',
    projectId: 'wasil-tech-task-5e36d',
    storageBucket: 'wasil-tech-task-5e36d.firebasestorage.app',
    iosBundleId: 'com.example.wasilTechTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYYTttZe41_BsZ9xnVxXiesQGoPIbbBD4',
    appId: '1:506716032293:web:fc7f3d93ce6e48b1fedecc',
    messagingSenderId: '506716032293',
    projectId: 'wasil-tech-task-5e36d',
    authDomain: 'wasil-tech-task-5e36d.firebaseapp.com',
    storageBucket: 'wasil-tech-task-5e36d.firebasestorage.app',
    measurementId: 'G-RWEVWS1XKH',
  );
}
